name = "ACEds"
uuid = "286ca7f0-9926-4809-930a-857c1b5bb5cd"
authors = ["Christoph Ortner <c.ortner@warwick.ac.uk> and Matthias Sachs <e.matthias.sachs@gmail.com>"]
version = "0.1.7"

[deps]
ACE = "3e8ccfd2-c8b0-11ea-32f1-f3a5990fd77a"
ACEatoms = "1e34e032-0b37-4839-a012-196b35408c3c"
ACEbase = "14bae519-eb20-449c-a949-9c58ed33163e"
ACEbonds = "d0dfcdf4-f9d4-4d39-8ac7-72ac73934171"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
FluxOptTools = "ca11d760-9bce-11e9-0b7e-4f72fcadb4f9"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
JuLIP = "945c410c-986d-556a-acb1-167a618e0462"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NeighbourLists = "2fcf5ba9-9ed4-57cf-b73f-ff513e316b9c"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Pandas = "eadc2687-ae89-51f9-a5d9-86b5a6373a9c"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
Tullio = "bc48ee85-29a4-5162-ae0b-a64e1601d4bc"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
ACE = "0.12.45"
ACEatoms = "0.0.14"
ACEbonds = "0.0.7"
JuLIP = "0.13.3"
StaticArrays = "1.0"
julia = "1.7"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "BenchmarkTools"]
