name = "ACEds"
uuid = "286ca7f0-9926-4809-930a-857c1b5bb5cd"
authors = ["Christoph Ortner <c.ortner@warwick.ac.uk> and contributors"]
version = "0.1.0"

[deps]
ACE = "3e8ccfd2-c8b0-11ea-32f1-f3a5990fd77a"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
JuLIP = "945c410c-986d-556a-acb1-167a618e0462"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
ACE = "0.8"
JuLIP = "0.10.0"
StaticArrays = "0.12"
julia = "1.4"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "BenchmarkTools"]
